Tendrl/gluster-integration

- run_travis.sh
Corrected the script to consider outputs
of pep8 and code coverage executions.
> Corrected the return value issue with script

- tendrl/gluster_bridge/tests/test_gluster_bridge.py
> Fixed test case error  

- doc/source/installation.rst
> Added logging related changes in installation guide

- tendrl/gluster_integration/manager/manager.py
- tendrl/gluster_integration/manager/tendrl_definitions_gluster.py
- tendrl/gluster_integration/manager/utils.py
- tendrl/gluster_integration/persistence/persister.py
- tendrl/gluster_integration/persistence/tendrl_context.py
- tendrl/gluster_integration/persistence/tendrl_definitions.py
- Used by ImportCluster/CreateCluster flow atoms
> Adds "--cluster-id" flag to startup cli

- tendrl/gluster_integration/objects/definition/gluster.py
> Corrected atom names and tendrl context fields

- tendrl/gluster_integration/central_store/__init__.py
- tendrl/gluster_integration/manager/manager.py
- tendrl/gluster_integration/objects/config/__init__.py
- tendrl/gluster_integration/objects/definition/__init__.py
> Added logic to persist definitions and config to central store

- tendrl/gluster_integration/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.py
> Fixed volume CRUD flows and atoms

- etc/tendrl/gluster-integration/gluster-integration.conf.yaml.sample
- tendrl/gluster_integration/flows/create_volume/__init__.py
- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/create/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/start/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/stop/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_started/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_stopped/__init__.py
- tendrl/gluster_integration/objects/volume/flows/delete_volume/__init__.py
- tendrl/gluster_integration/objects/volume/flows/start_volume/__init__.py
- tendrl/gluster_integration/objects/volume/flows/stop_volume/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#140
> Added in flight operation job update messages

- tendrl/gluster_integration/__init__.py
- tendrl/gluster_integration/central_store/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.py
- tendrl/gluster_integration/objects/utilization/__init__.py
- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
> Added cluster and volume utilization details

- etc/tendrl/gluster-integration/gluster-integration.conf.yaml.sample
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>
> Fix message socket path in sample conf

- tendrl/gluster_integration/objects/definition/gluster.py
- tendrl/gluster_integration/objects/utilization/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
> Added extra check while gstatus run and percent use of cluster

- tendrl/gluster_integration/__init__.py
- tendrl/gluster_integration/objects/definition/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.py
- tendrl/gluster_integration/objects/volume/atoms/named_volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_started/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_stopped/__init__.py
> Added pre/post runs for volume crud operations

- dependencies/gstatus/Makefile
tendrl-bug-id: Tendrl/gluster-integration#151
> Packaging: adding make file for gstatus package build

- tendrl/gluster_integration/sds_sync/__init__.py
Due to and issue in utilization details syncing for the volume,
it was creating a blank volume data under /cluster/{id}/Volumes
level itself. Fixed the same.
tendrl-bug-id: Tendrl/gluster-integration#162
> Fixed issue with volume details syncing.

- tendrl/gluster_integration/objects/volume/atoms/named_volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_started/__init__.py
> Fixed an issue with pre run atoms

- setup.py
- tendrl/gluster_integration/objects/definition/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
tendrl-bug-id: Tendrl/gluster-integration#187
> Removed yaml content from py files

- tendrl/gluster_integration/objects/definition/gluster.yaml
> Corrected the definition of Peer object

- setup.py
> Corrected setup.py

- tendrl/gluster_integration/manager/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#199
> Added logic to populate cluster_name and cluster_id under TendrlContext

- etc/tendrl/gluster-integration/gluster-integration.conf.yaml.sample
- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/peer/__init__.py
- tendrl/gluster_integration/objects/sync_object/__init__.py
- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/objects/volume_options/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/specifications#28
tendrl-spec: Tendrl/specifications#127
Signed-off-by: anmolsachan asachan@redhat.com
> Logging changes according to new logging framework

- tendrl/gluster_integration/objects/definition/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
> Modified gluster integration to support object validation

- tendrl/gluster_integration/gdeploy_wrapper/plugins/gdeploy.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
> Fixed service start issue due to definitions

- tendrl/gluster_integration/gdeploy_wrapper/plugins/gdeploy.py
Fix the typo, it causes issue for EC Volume creation
> Fixing the Typo

- tendrl-gluster-integration.service
- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_not_exists/__init__.py
Also added enviornment variable `ANSIBLE_HOST_KEY_CHECKING=False`
for making sure first time gdeploy execution doesnt ask for
confirmation to connect to node.
> Corrected check for non-existence of volume after delete

- tendrl/gluster_integration/sds_sync/__init__.py
In case there are no volumes in the cluster, gstatus doesnt return
the utilization and status details for the underlying cluster.
Added logic to calculate the status based on peer's connected status
and utilization to default to zeros.
> Added default status and utilization for cluster with no volumes

- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
The volume lock that is acquired, should have a ttl
So that, even if the service is ended abruptly. The
lock wont end up for ever, as there is no one to
release it.
tendrl-bug-id: Tendrl/gluster-integration#237
> Set ttl for the volume lock that we acquire

- tendrl/gluster_integration/gdeploy_wrapper/plugins/gdeploy.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/atoms/rebalance_not_running/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/rebalance_running/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/start_rebalance/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/stop_rebalance/__init__.py
- tendrl/gluster_integration/objects/volume/flows/start_volume_rebalance/__init__.py
- tendrl/gluster_integration/objects/volume/flows/stop_volume_rebalance/__init__.py
The status of the rebalance would be taken care as part of
cluster data sync.
> Added flows and atoms for starting/stopping volume rebalance

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/global_details/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
Signed-off-by: root <root@dhcp43-149.lab.eng.blr.redhat.com>
> Added connection details and volume degraded details in sync

- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_utilization.py
Signed-off-by: root <root@dhcp43-187.lab.eng.blr.redhat.com>
> Brick utilization during sds sync

- tendrl/gluster_integration/sds_sync/__init__.py
> Fixing brick sync issue

- tendrl/gluster_integration/objects/volume/atoms/create/__init__.py
Signed-off-by: root <root@dhcp42-191.lab.eng.blr.redhat.com>
> Identifying node_id using hostname also in volume creation

- tendrl/gluster_integration/gdeploy_wrapper/plugins/gdeploy.py
Change the type of message from error to info.
> Fix the type of message

- tendrl/gluster_integration/flows/create_brick/__init__.py
- tendrl/gluster_integration/flows/create_volume/__init__.py
- tendrl/gluster_integration/gdeploy_wrapper/manager.py
- tendrl/gluster_integration/gdeploy_wrapper/plugins/gdeploy.py
- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/named_volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/rebalance_not_running/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/validate_expand_volume_inputs/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/validate_shrink_volume_inputs/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_started/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_stopped/__init__.py
- tendrl/gluster_integration/objects/volume/flows/stop_volume_rebalance/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_utilization.py
tendrl-bug-id: Tendrl/commons#575
> Re-align priorities for current log msgs

- tendrl-gluster-integration.spec
tendrl-bug-id: Tendrl/gluster-integration#294
> Added systemctl enable for service in post section

- etc/rebalance_jobs/start_volume_rebalance.py
- etc/rebalance_jobs/stop_volume_rebalance.py
tendrl-bug-id: Tendrl/gluster-integration#300
> Added sample jobs for rebalance operations

- tendrl/gluster_integration/objects/volume/atoms/check_volume_available/__init__.py
Fix local variable "volumes" used before assignment issue
> Fixed an issue with post run of volume creation

- etc/tendrl/gluster-integration/gluster-integration.conf.yaml.sample
- tendrl/gluster_integration/manager/__init__.py
tendrl-bug-id: Tendrl/commons#612
> provide config flag to turn on profiling

- tendrl/gluster_integration/objects/definition/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#309
> Multiple calls to gluster.objects.Definition.get_parsed_defs()

- etc/get_brick_mapping.py
- tendrl/gluster_integration/flows/generate_brick_mapping/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/atoms/generate_brick_mapping/__init__.py
This patch adds a new flow for getting the brick mapping needed for gluster volume creation as per the best practices. It takes the list of nodes, number of brick per node and size of the sub volume as the input and returns a list of sub volumes.
tendrl-bug-id: Tendrl/gluster-integration#292
> Brick layouting flow2

- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#266
tendrl-bug-id: Tendrl/gluster-integration#279
Lock code is removed because ttl will tack care of out of band deletion 
Signed-off-by: root <gshanmug@redhat.com>
> Out of band deletion for volume, brick and peer

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#321
> Added logic to sync cluster network details while import

- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/rebalance_running/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
tendrl-bug-id: Tendrl/gluster-integration#323
> Add a volume level rebalance status field

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/client_connections.py
- tendrl/gluster_integration/sds_sync/cluster_status.py
- tendrl/gluster_integration/sds_sync/event_utils.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
tendrl-bug-id: Tendrl/specifications#167
> Moved `emit_event` to module event_utils.py

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#330
> Fix pep8 issues

- tendrl/gluster_integration/sds_sync/__init__.py
> Assign a blank list if no volumes

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#383
> Initailize the volumes list as empty list if no volumes

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
tendrl-bug-id: Tendrl/gluster-integration#376
> Calculate volume rebalance status from node specific rebalance details

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#385
> Added logic to invoke update dashboard flow from monitoring integration

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/event_utils.py
> Regression fix with emit_event

- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#394
> Save volume same as an attribute of brick object

- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/brick/atoms/create/__init__.py
- tendrl/gluster_integration/objects/client_connection/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/atoms/create/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/generate_brick_mapping/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_device_details.py
- tendrl/gluster_integration/sds_sync/client_connections.py
- tendrl/gluster_integration/sds_sync/cluster_status.py
- tendrl/gluster_integration/sds_sync/utilization.py
This patch makes sure that brick object is
accessed in the modified location after the
path change.
tendrl-bug-id: Tendrl/gluster-integration#388
> Modify access path of brick object.

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/peer/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/event_utils.py
- tendrl/gluster_integration/sds_sync/georep_details.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
Alerts added for
- rebelance status changes
- geo-rep session status changes
- volume status changes
- brick status changes
- peer status changes
> Added alerts for status changes

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#403
> Added message handlers for brick/volume/peers

- tendrl/gluster_integration/sds_sync/event_utils.py
> Added alerting conditions in alert message

- tendrl/gluster_integration/sds_sync/cluster_status.py
tendrl-bug-id:Tendrl/gluster-integration#407
Fixed the typo
> volume sync - fixes

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/process_events.py
- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/native_events/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/event_utils.py
This patch adds handlers for gluster native
events
tendrl-bug-id: Tendrl/specifications#180
tendrl-bug-id: Tendrl/gluster-integration#361
> Add handlers to native events

- tendrl/gluster_integration/message/process_events.py
- tendrl/gluster_integration/objects/native_events/__init__.py
> Fixed None checks with native events

- tendrl/gluster_integration/manager/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#419
> Stop GlusterIntegrationManager on service termination

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/process_events.py
- tendrl/gluster_integration/sds_sync/__init__.py
This patch fixes some typos, pep8 issues. Also Now
the context will have type "-" object_name for better
readability
tendrl-bug-id: Tendrl/gluster-integration#361
> Fix readability/typo/pep8 issues

- tendrl/gluster_integration/message/callback.py
This patch fixes parsing issues in message
handler. Also adds clear message for geo-rep
checkpoint completion.
tendrl-bug-id: Tendrl/gluster-integration#361
> Fix parsing issue in message handler

- tendrl/gluster_integration/message/callback.py
tendrl-bug-id: Tendrl/gluster-integration#437
> Invoke update graphite while deletion of peer/vol/brick

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/peer/__init__.py
- tendrl/gluster_integration/objects/volume/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#439
> Modified to set deleted flag while peer/vol/brick deletion

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume_alert_counters/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bugid: Tendrl/gluster-integration#447
> alert counter to be initialized even the alert count is zero

- setup.py
- tendrl-gluster-integration.spec
- tendrl/gluster_integration/gfapi.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
tendrl-bug-id: Tendrl/gluster-integration#446
> Changed the logic to gfapi for volume utilization

- tendrl/gluster_integration/gfapi.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
> Calculate and set TTL for entities based on no of volumes

- tendrl/gluster_integration/gfapi.py
- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/gluster_native_message_handler.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
> Pep8 fixes

- tendrl/gluster_integration/sds_sync/cluster_status.py
> Changed the logic of calculating the cluster status

- tendrl/gluster_integration/message/gluster_native_message_handler.py
This patch corrects severity of events related to
setting up the webhooks for gluster events api
> Correct the severity of messages.

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bugid: Tendrl/gluster-integration#461
> Added integration id in alert message

- tendrl/gluster_integration/sds_sync/georep_details.py
tendrl-bug-id: Tendrl/gluster-integration#459
> Fixes around georep session status

- tendrl/gluster_integration/message/callback.py
tendrl-bugid: Tendrl/gluster-integration#470
> volume and brick dashboards are deleted when volumes are deleted

- tendrl/gluster_integration/sds_sync/__init__.py
Tendrl-bugid: Tendrl/gluster-integration#465
> Omitting deleted volumes while collection global cluster details

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bugid: Tendrl/gluster-integration#475
> fix sync error in gluster-integration

- tendrl/gluster_integration/sds_sync/client_connections.py
tendrl-bugid: Tendrl/gluster-integration#483
> Fixing bug in gluster-integration sync while delete volume

- tendrl/gluster_integration/sds_sync/georep_details.py
tendrl-bug-id: Tendrl/gluster-integration#459
> Fix geo-rep session status aggregation logic

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#489
> Dont raise exception is sds sync cycle

- tendrl/gluster_integration/message/callback.py
tendrl-bugid: Tendrl/gluster-integration#501
> Added Replace brick handler

- tendrl-gluster-integration.spec
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1517079
> Fix package update issue during rpm test for TPS

- tendrl/gluster_integration/message/callback.py
> Corrected the positional arugments for format function

- tendrl/gluster_integration/sds_sync/cluster_status.py
tendrl-bug-id: Tendrl/gluster-integration#512
> Corrected the volume state changes alerting logic

- tendrl/gluster_integration/sds_sync/cluster_status.py
tendrl-bug-id: Tendrl/gluster-integration#507
> Added alerts for cluster status changes

- tendrl/gluster_integration/message/callback.py
tendrl-bug-id: Tendrl/gluster-integration#518
> Remove stale bricks after snapshot restore

- tendrl/gluster_integration/sds_sync/cluster_status.py
> Fixed an issue with gluster volume state change alerts

- tendrl/gluster_integration/sds_sync/rebalance_status.py
* Aggregation was not considering arbiter volume as we had a check for "distribute" in vol type and arbiter volume has "arbiter" as type
* Earlier our understanding was, get state would report rebalance related info for only nodes that were involved in rebalance for a volume. But it reports info about rebalance on all the cluster nodes and if node is not part of rebalance operation it reports the default values (for status its `not stated`) Which messes up the calculation of aggregated status.
This PR rectifies these 2 issues
tendrl-bug-id: Tendrl/gluster-integration#497
> Include arbiter volume for rebalance aggregation

- tendrl/gluster_integration/objects/global_details/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/cluster_status.py
> Set TTL for cluster status and handle it accordingly

- tendrl/gluster_integration/objects/global_details/__init__.py
> Corrected cluster status changes

- tendrl/gluster_integration/sds_sync/__init__.py
> Changed the logic for sync_ttl for cluster entities

- tendrl/gluster_integration/sds_sync/rebalance_status.py
tendrl-bug-id: Tendrl/gluster-integration#537
> Typecast volume attrs before comparing

- tendrl/gluster_integration/message/callback.py
tendrl-bugid: Tendrl/gluster-integration#542
> svc clearing info alert doesn't remove warning alert

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bugid: Tendrl/gluster-integration#548
> Raising brick alert when peer is disconnected or node goes down

- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/commons#797
> Added changes for new cluster objects attributes

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/start_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/stop_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/flows/start_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/flows/stop_profiling/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#553
> Added logic to consider profiling enabled for few volumes

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#568
> Set ClusterNodeContext.is_managed during sync

- tendrl/gluster_integration/objects/volume/atoms/start_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/stop_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/flows/start_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/flows/stop_profiling/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#553
> Corrected issue while setting current job status

- tendrl/gluster_integration/objects/volume/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#575
> Changed default volume deleted flag from False to None

- tendrl/gluster_integration/sds_sync/__init__.py
> During expansion gluster integration sds sync should be allowed

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#580
> Check the old value of volume profiling and then raise event

- tendrl/gluster_integration/flows/enable_disable_volume_profiling/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/atoms/start_profiling/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/stop_profiling/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#592
> Added a flow for setting volume profiling for all the volumes

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/commons#881
> Added logic to not write cluster objects if some active jobs

- tendrl/gluster_integration/sds_sync/cluster_status.py
tendrl-bug-id: Tendrl/commons#874
> Set the cluster status as unhealthy is import failed earlier

- tendrl/gluster_integration/sds_sync/__init__.py
> Added a check for cluster status as well while saving

- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/tests/test_manager.py
tendrl-bug-id: Tendrl/gluster-integration#600
> Removed references of gdeploy from code

- tendrl/gluster_integration/objects/volume/atoms/check_volume_available/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/expand/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/generate_brick_mapping/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/named_volume_not_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/shrink/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/validate_expand_volume_inputs/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/validate_shrink_volume_inputs/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_exists/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_started/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/volume_stopped/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/georep_details.py
tendrl-bug-id: Tendrl/gluster-integration#603
> Remove import statements for gluster-integration objects

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/tests/message/test_callback.py
tendrl-bug-id: Tendrl/gluster-integration#612
Signed-off-by: Gowthamshanmugasundaram <gshanmug@redhat.com>
> Changing gluster event handling logic based on fqdn/ip change

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/cluster_status.py
- tendrl/gluster_integration/sds_sync/georep_details.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
- tendrl/gluster_integration/tests/test_event_utils.py
- tendrl/gluster_integration/tests/test_sds_sync.py
tendrl-bug-id:Tendrl/gluster-integration/issues/607
> Improved alert messages

- setup.py
- tendrl-gluster-integration.spec
- tendrl/gluster_integration/message/gluster_native_message_handler.py
tendrl-bug-id: Tendrl/gluster-integration#629
> Use cherrypy for gluster native events webhook

- tendrl/gluster_integration/message/gluster_native_message_handler.py
- tendrl/gluster_integration/sds_sync/__init__.py
Signed-off-by: anmolsachan asachan@redhat.com
> Fixed PEP-8 errors

- tendrl/gluster_integration/sds_sync/brick_device_details.py
bugzilla: 1578329
tendrl-bug-id: Tendrl/gluster-integration#642
> Brick details are not displayed in UI

- tendrl/gluster_integration/flows/enable_disable_volume_profiling/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#636
Bugzilla-id: https://bugzilla.redhat.com/1578333
> Dont set cluster level profiling flag if volume level flags Unknown

- tendrl/gluster_integration/manager/__init__.py
Bugzilla-id: https://bugzilla.redhat.com/1581324
tendrl-bug-id: Tendrl/gluster-integration#646
> Fixed an exception while stopping the service

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#652
bugzilla: 1571755
> Cluster status related alert notification use integration id instead of cluster name

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration/issues/650
bugzilla: 1570048
> When child job fails in provisioner node then other child job are not responding

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/tests/message/test_callback.py
- tendrl/gluster_integration/tests/message/test_gluster_native_message_handler.py
- tendrl/gluster_integration/tests/test_client_connections.py
- tendrl/gluster_integration/tests/test_init.py
- tendrl/gluster_integration/tests/test_sds_sync.py
tendrl-bug-id: Tendrl/gluster-integration#657
> Fixed gluster integration testcases

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#662
bugzilla: 1588440
> Sometimes volume alert raise with name None

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#659
bugzilla: 1519201
> After node up peer alert is not replaced by clearing alert

- Makefile
- tendrl-gluster-integration.spec
> rel_prep 1.6.3-6

- setup.py
- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
- tendrl/gluster_integration/tests/test_gluster_integration.py
- tendrl/gluster_integration/tests/test_volume_utilization.py
tendrl-bug-id: Tendrl/gluster-integration#669
bugzilla: 1596862
> Improve gluster integration sync execution performance

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#669
bugzilla: 1596862
> Adjusting volume TTL value

- tendrl/gluster_integration/sds_sync/georep_details.py
There is no field with name `key`. We need to refer the field
value for the session_id for further calculation of pairs of
the geo replication session. Corrected the same as part this
change.
tendrl-bug-id: Tendrl/gluster-integration#684
bugzilla: 1603175
> Fixed GeoReplicationSession field reference

- Makefile
- tendrl-gluster-integration.spec
> rel_prep/1.6.3-9

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/tests/test_volume_utilization.py
tendrl-bug-id: Tendrl/gluster-integration#690
bugzilla: 1596655
> Fix cluster object race condition issue

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/tests/message/test_callback.py
tendrl-bug-id: Tendrl/gluster-integration#694
bugzilla: 1616215, 1616208
> Raising svc_connected and svc_disconnected for all nodes in a cluster

- tendrl/gluster_integration/sds_sync/utilization.py
tendrl-bug-id: Tendrl/gluster-integration#699
bugzilla: 1628878
> Fixing issue: Volume Capacity Utilization not working on RHEL 7.6. Beta

- tendrl/gluster_integration/objects/global_details/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/georep_details.py
- tendrl/gluster_integration/sds_sync/rebalance_status.py
- tendrl/gluster_integration/sds_sync/utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
Fixed Volume Utilization calculation for other volumes when all the bricks in one of the volumes are down.
Bugzilla-id : 1641413
tendrl-bug-id: Tendrl/gluster-integration#705
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>
> Fixed Volume Utilization calculation for other volumes

- tendrl/gluster_integration/tests/test_volume_utilization.py
bugzilla-id: 1641413
tendrl-bug-id: Tendrl/gluster-integration#705
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>
> Fixed Test Case for Volume Utilization Calculation

- tendrl/gluster_integration/message/callback.py
tendrl-bug-id: Tendrl/gluster-integration#722
bugzilla: 1666386
> Processing split-brain related events based on client-pid
