- doc/source/installation.rst
- setup.py
- tendrl/gluster_bridge/log.py
Signed-off-by: Shubhendu shtripat@redhat.com
> Added few more details for installation guidelines

- tendrl/gluster_bridge/manager/manager.py
- tendrl/gluster_bridge/persistence/persister.py
- tendrl/gluster_bridge/persistence/servers.py
- tendrl/gluster_bridge/persistence/sync_objects.py
- tendrl/gluster_bridge/tests/test_manager.py
- tendrl/gluster_bridge/tests/test_persister.py
- tendrl/gluster_bridge/tests/test_servers.py
There were various below listed issues which are fixed
as part of this patch
- raw_data for the cluster was not getting written to
etcd due to argument replacement issue
- render() was missing in class SyncObject
- no cluster id getting used in etcd keys
- primary hostname is used as peer name
- the function update_sync_object() was not referred with
correct name in manager.py
Also standardized the etcd keys as below
- /clusters/<cluster-id>/peers/<peer-id>
- /clusters/<cluster-id>/volumes/<volume-id>
- /clusters/<cluster-id>/volumes/<volume-id>/bricks/<brick-id>
- /clusters/<cluster-id>/raw_data
> Fixed issues with persister and standardized etcd keys

- tendrl-gluster-integration.spec
This file is not an executable. Do not install it as such.
This fixes the following rpmlint error:
```
E: script-without-shebang
/usr/share/tendrl/gluster_integration/tendrl.conf.sample
```
Reported-by: @mkudlej
> rpm: install tendrl.sample as non-executable

- tendrl/gluster_integration/manager/rpc.py
- tendrl/gluster_integration/tests/test_rpc.py
Instead of the exception, EtcdKeyNotFound is logged successfully
tendrl-bug-id:Tendrl/gluster_integration#26
Signed-off-by: root <gshanmug@redhat.com>
> Logged EtcdKeyNotFound exception from rpc.py

- tendrl/gluster_integration/manager/manager.py
- tendrl/gluster_integration/manager/tendrl_definitions_gluster.py
- tendrl/gluster_integration/persistence/servers.py
- tendrl/gluster_integration/tests/test_manager.py
- tendrl/gluster_integration/tests/test_servers.py
As per new output from gluster get-state command, volume
option details are listed. Modiifed to parse and populate
the volume options details to the central store.
tendrl-bug-id: gluster_integration/#41
tendrl-spec: refactor_gluster_integration_get_state_dump.adoc
> Added logic to populate volume options to central store

- tendrl/gluster_integration/manager/__init__.py
Get SIGTERM value form signal module instead of
gevent.signal. Its not available in later
> Fix Unavailable gevent.signal.SIGTERM issue

- tendrl-glusterd.service
Set the HOME variable path to /var/lib/tendrl
tendrl-bug-id: Tendrl/gluster-integration#131
> Fix service start issue due to environment variable issue

- tendrl/gluster_integration/objects/tendrl_context/__init__.py
We should have a field called integration name under
TendrlContext object to indicate cluster name. Since
glusterfs backend does not have a concept of cluster
name, its generated using integration_id as follows:
"glusterfs_<integration-id>" whaere integration_id is
tendrl generated cluster id.
tendrl-bug-id: Tendrl/gluster-integration#143
> Have a field for cluster name under tendrl-context.

- tendrl/gluster_integration/objects/definition/gluster.py
This patch adds missing entries for tendrl context attributes in the definition file
https://github.com/Tendrl/gluster-integration/issues/143
> Added Missing entries for TendrlContext attributes

- tendrl/gluster_integration/sds_sync/__init__.py
Due to this cluster status and volume utlization details
were not being synced while regular sync.
tendrl-bug-id: Tendrl/gluster-integration#217
> Added import for `os` as it was removed as a regression

- tendrl/gluster_integration/objects/definition/gluster.yaml
All gluster CRUD jobs have to be targeted to Provisioner node. So modifying the tags accordingly
> Fix the job target tags for CRUD flows

- tendrl/gluster_integration/objects/volume/atoms/delete/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
This PR adds locking while deleting a volume, to
avoid the addition of details of deleted volume by
sds sync thread of other gluster integration process
tendrl-bug-id: Tendrl/api#78
> Added Locking while deleting gluster volume

- tendrl/gluster_integration/sds_sync/__init__.py
The order of gluster volume bricks is important
because, we figure out the sub-volume details by
seeing the order of bricks. The bricks were not
ordered before, this patch makes sure we save the
bricks in order
tendrl-bug-id: Tendrl/gluster-integration#236
> Store the gluster volume bricks in order

- tendrl/gluster_integration/sds_sync/__init__.py
Make sure default status update doesnt fail with exception
even if gstatus return bogus data.
tendrl-bug-id: Tendrl/gluster-integration#245
> Added check for proper output of gstatus

- tendrl/gluster_integration/flows/create_brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/gluster_brick/__init__.py
- tendrl/gluster_integration/objects/gluster_brick/atoms/create/__init__.py
- tendrl/gluster_integration/objects/gluster_brick_path/__init__.py
- tendrl/gluster_integration/objects/volume/atoms/create/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
This patch classifies the gluster bricks as used and
free based on if its used in a gluster volume. Also
this patch adds a cluster level object to hold the
default gluster brick path
tendrl-bug-id: https://github.com/Tendrl/gluster-integration/issues/252
> Classify bricks gluster bricks as used/free

- tendrl/gluster_integration/objects/volume/atoms/create/__init__.py
Volume create flow had following 2 issues:
1. Volume was explicitly started after create. We need not
do this as gdeploy starts a volume when created. This was
causing a failure as we tried starting a started volume.
2. While marking bricks as used, the path was not correctly
composed.
This patch fixes above 2 issues
> Fix Volume create flow.

- tendrl/gluster_integration/sds_sync/__init__.py
This patch sends alerts when the status of volume/bricks
changes. Both from healthy to unhealthy and vice versa
tendrl-bug-id: Tendrl/gluster-integration#286
> Raise alerts for volume/brick status change.

- tendrl/gluster_integration/objects/definition/gluster.yaml
This patch adds the missing target tags for gluster volume rebalance actions
Tendrl-bug-id: https://github.com/Tendrl/gluster-integration/issues/299
> Set target tags for gluster volume rebalance flows

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/atoms/check_volume_available/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#296
> Added post checks to check if object are available in etcd post create

- Makefile
- tendrl-gluster-integration.spec
Update makefile for snapshot srpm version to have timestamp
and shortcommit
tendrl-bug-id: Tendrl/gluster-integration#348
> Packaging: snapshot srpm version with timestamp and shortcommit

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/geo_replication_pair/__init__.py
- tendrl/gluster_integration/objects/geo_replication_session/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/georep_details.py
This patch adds methods and objects for syncing gluster
geo replication session related details under volume in
etcd.
tendrl-bug-id: Tendrl/specifications#167
tendrl-bug-id: Tendrl/gluster-integration#340
> Add geo replication session details in etcd

- tendrl-gluster-integration.spec
- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_device_details.py
This patch gathers the gluster brick device details and
updates it during the sds sync. It uses blivet to gather
the node's storage device details.
Using the brick path the brick mount-point and filesystem
is gathered first. using these details we search for the
brick device in blivet's devicetree. Blivet's device tree
will have the details about the underlying device.
tendrl-bug-id: Tendrl/gluster-integration#333
tendrl-bug-id: Tendrl/specifications#173
> Update brick device details as part of sync.

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
If cluster level flag is set to enable profiling, while syncing
the cluster volumes, profiling would be enabled for all the
volumes, else disabled.
tendrl-bug-id: Tendrl/gluster-integration#353
> Added logic to enable / disable volume profiling

- tendrl/gluster_integration/sds_sync/rebalance_status.py
Earlier rebalance status was calculated for only pure distribute volume. Now it has been edited to gather status for all types of distribute volume
> Find rebalance status for all distribute volumes

- tendrl/gluster_integration/sds_sync/rebalance_status.py
This is to make sure even if command fails due to transient
collisions, we retry at least no of times.
tendrl-bug-id: Tendrl/gluster-integration#374
> Added retry option for `gluster v status` command

- tendrl/gluster_integration/objects/brick/__init__.py
Currently the brick details are saved at:
clusters/<cluster-id>/bricks/all/<host:brick-dir-path>
This PR changes the path to:
clusters/<cluster-id>/bricks/all/<host>/<brick-dir-path>.
The reason for this change is API can easily get a list
of all bricks under a host with the new structure.
tendrl-bug-id: Tendrl/gluster-integration#388
> Change the path where brick details are saved.

- tendrl-gluster-integration.spec
- tendrl/gluster_integration/manager/__init__.py
- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/gluster_native_message_handler.py
This patch adds a mechanism in gluster integration to
receive gluster native events that are pushed by
glustereventsd. It also takes care of setup and cleanup
of webhooks needed for recieving events. This patch also
adds place holders for few sample event handler functions
tendrl-bug-id: Tendrl/specifications#180
tendrl-bug-id: Tendrl/gluster-integration#361
> Enable gluster native events in tendrl.

- tendrl/gluster_integration/sds_sync/brick_device_details.py
If attributes are of unicode type, its causing issues
in API layer.
tendrl-bug-id: Tendrl/gluster-integration#400
> Change unicode attrs in brick obj to string.

- tendrl/gluster_integration/message/callback.py
While invoking update dashboard flow for brick add/delete, the
monitoring-integration needs volume name as well. Added the volume
name as part resource_name parameter of the flow in the form
`{vol_name}|{brick-host-name}:{brick-path}`
tendrl-bug-id: Tendrl/gluster-integration#413
> Added volume name as well in resource while brick add/delete

- MANIFEST.in
Fix no rule to make target bzip-selinux-policy error during rpm build.
tendrl-bug-id: Tendrl/gluster-integration#421
> Packaging: Fix build failure due to missing bzip-selinux-policy target

- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/sds_sync/brick_device_details.py
This patch adds a new attribute for brick object
for storing the brick's partition information.
As its needed for calculating io stats.
tendrl-bug-id: Tendrl/gluster-integration#425
> Save brick partition information.

- tendrl/gluster_integration/sds_sync/__init__.py
If profiling is already started for few volumes from CLI and we
import the cluster, by no means these volumes were marked as
profiling on in tendrl. Modified to tackle this scenario.
tendrl-bug-id: Tendrl/gluster-integration#418
> Added logic to check already started/stopped profiling for volumes

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/gluster_native_message_handler.py
gluster native events that are being ignored by
gluster integration are not handled correctly, this
is causing an exception in event listener. Which in
turn is leading to an `500 internal server error` in
glusterfs events.log
tendrl-bug-id: Tendrl/gluster-integration#433
> Handle ignored native events properly.

- tendrl/gluster_integration/flows/update_brick_status/__init__.py
- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/sds_sync/__init__.py
This patch adds a new flow UpdateBrickStatus
that updates the status of bricks of a given
node as "Stopped". This flow is invoked for
nodes that are down.
tendrl-bug-id: Tendrl/monitoring-integration#169
> Add flow to update brick status as stopped.

- tendrl/gluster_integration/message/callback.py
- tendrl/gluster_integration/message/process_events.py
- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/native_events/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/event_utils.py
tendrl-bugid: Tendrl/gluster-integration#452
tendrl-bugid: Tendrl/gluster-integration#449
> Modifying alerting logic based on alert classifications

- tendrl/gluster_integration/message/callback.py
This patch makes sure that the brick related info
in removed from etcd once the brick is removed from
the volume or the volume itself is deleted.
tendrl-bug-id: Tendrl/monitoring-integration#169
> Remove brick information from etcd on removal

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/volume/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
Currently volume inode usage details are not
collected. This patch takes care of that by
adding attributes to volume object that hold
inode usage info. This is being collected
through libgfapi.
tendrl-bug-id: Tendrl/gluster-integration#481
> Collect inode usage details for volume

- tendrl/gluster_integration/message/callback.py
As part of remove brick handler we are deleting all the brick
related information, so that next sync takes care of updating
the correct info
tendrl-bug-id: Tendrl/gluster-integration#494
> Handle remove brick correctly when subvolume number shifts

- tendrl/gluster_integration/sds_sync/rebalance_status.py
Currently rebalance status is not aggregated correctly
as few states are missing. This patch takes care of
that.
tendrl-bug-id: Tendrl/gluster-integration#497
> Rebalance status aggregation fix

- tendrl/gluster_integration/message/callback.py
This patch changes the invocation of dashboard
deletion flow from peer disconnect to peer detach.
As peer detach is the user triggered action
tendrl-bug-id: Tendrl/gluster-integration#516
> Invoke job to delete dashboard on peer_detach

- tendrl/gluster_integration/message/callback.py
peer reject event gives peer name along with a number
appended to it. This is handled correctly by this patch
tendrl-bug-id: Tendrl/gluster-integration#514
> Handle peer reject event correctly

- tendrl/gluster_integration/objects/brick/__init__.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/brick_device_details.py
Add ttl to brick status attribute. Because if all the
nodes in the cluster goes down, the status will remain
as up and the same info will be displayed in dashboard.
To avoid this we set ttl, so thet dashboard can clearly
indicate the staleness of the field
tendrl-bug-id: Tendrl/gluster-integration#525
> Add ttl to brick status attribute.

- tendrl/gluster_integration/sds_sync/__init__.py
Instead of setting cluster.is_managed post sync, now set the field
first_sync_done only for the first time. This makes sure import
cluster flow gets completed only once all the storages nodes report
their first sync done.
tendrl-bug-id: Tendrl/commons#829
> Set first_sync_done once first sync gets over for cluster

- tendrl/gluster_integration/objects/definition/gluster.yaml
> volname is not required in start/stop profiling calls

- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#589
> Initializing cluster_node_alert count in gluster_integration sync

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/sds_sync/__init__.py
tendrl-bug-id: Tendrl/gluster-integration#598
> Calculating and updtating cluster and volume alert_count in each cluster sync

- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/tests/test_sds_sync.py
tendrl-bug-id: Tendrl/gluster-integration#609
Signed-off-by: Gowthamshanmugasundaram <gshanmug@redhat.com>
> Populating brick details correctly when peer hostname and brick hostname not match

- tendrl/gluster_integration/sds_sync/__init__.py
Every sync time creating a fresh object and saving is not correct.
If object exists, load the same and update the values in object
before save. This makes sure no derived fields get reset every
sync time again and again.
tendrl-bug-id: Tendrl/gluster-integration#619
> Load and save volume object

- tendrl/gluster_integration/flows/enable_disable_volume_profiling/__init__.py
In case profiling is already enabled for a volume, enable command
fails for the same. In the flow these are logged as errors in task.
Changed the logic to log the messages and info as its actually not
a failure.
tendrl-bug-id: Tendrl/gluster-integration#631
Bugzilla-id: https://bugzilla.redhat.com/1577228
> Changed to log the message as info if profile flag setting errors out

- tendrl/gluster_integration/sds_sync/__init__.py
When new peer probe is done then all nodes raises peer connected info
event, so multiple events are displayed in UI. As per logic in
https://github.com/Tendrl/node-agent/pull/817 first non-info alert
raised then it will start comparing with an old alert to avoid duplicate
events but here actually info alert is raised first, so node-agent handler
does not have any old alert to avoid duplicate. And also we have a check to
avoid first info alert but it is wrong None == "" won't match.
I have corrected the logic here.
bugzilla: 1579937
tendrl-bug-id: Tendrl/gluster-integration#648
> Multiple peer connected events when new peer probe is done in managed cluster

- tendrl/gluster_integration/manager/__init__.py
Inside message handler constructor we are finding cluster_name
using integration_id, if it before called integration_id found then
it will raise alert with None
tendrl-bug-id: Tendrl/gluster-integration#662
bugzilla: 1588440
> Creating native message handler object after integration_id found

- tendrl/gluster_integration/sds_sync/__init__.py
It is one more corner case problem, the problem is we
down all storage nodes and after volume are deleted by
TTL then we are starting all the nodes, what is happening
all storage nodes are pushing volume_rebalance data into
etcd before we decide provisioner. now volume entry present
with rebalance directory but there are no details about
volume because volume details are populated by provisioner
only. but provisioner is decided in-between of execution
then global details are executed before volume details
populate. so alert raised with name None.
tendrl-bug-id: Tendrl/gluster-integration#667
bugzilla: 1595295
> Volume alert raised with volume name None

- setup.py
- tendrl/gluster_integration/sds_sync/__init__.py
- tendrl/gluster_integration/sds_sync/utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
- tendrl/gluster_integration/tests/test_volume_utilization.py
There seems to be some meory leaks in gfapi and due to that if we
make in-memory calls to gfapi, the memory utilization on the nodes
keeps increasing slowly. If we make subprocess call this increase would
be eventual and no overall increase happens to the memory utilization
of the node.
tendrl-bug-id: Tendrl/gluster-integration#681
bugzilla: 1599987
> Invoke volume utilization calculation as subprocess

- tendrl/gluster_integration/objects/definition/gluster.yaml
- tendrl/gluster_integration/objects/geo_replication_session/__init__.py
This is changed based on common's GeoReplicationSession object
tendrl-bug-id: Tendrl/gluster-integration#686
bugzilla: 1603175
> Adding integration_id in GeoReplicationSession object

- tendrl/gluster_integration/sds_sync/brick_utilization.py
- tendrl/gluster_integration/sds_sync/vol_utilization.py
bugzilla: 1683603
tendrl-bug-id: Tendrl/gluster-integration#715
> Import cluster is failing when one or more storage nodes does not have at least one lvm

- tendrl/gluster_integration/sds_sync/__init__.py
>  Blocking gluster-integration sync when gluster-integration is started before fire importflow
